/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prog_exer1;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author jjppatrimonio
 */
public class Products extends javax.swing.JFrame {

    /**
     * Creates new form Products
     */
    public Products() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        prodID = new javax.swing.JTextField();
        prodType = new javax.swing.JTextField();
        prodDESC = new javax.swing.JTextField();
        prodSUP = new javax.swing.JTextField();
        prodQUANT = new javax.swing.JTextField();
        prodTC = new javax.swing.JTextField();
        prodDATE = new javax.swing.JTextField();
        save = new javax.swing.JToggleButton();
        qLabel = new javax.swing.JLabel();
        tcLabel = new javax.swing.JLabel();
        dLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Product ID:");

        jLabel2.setText("Product Type:");

        jLabel3.setText("Product Description:");

        jLabel4.setText("Supplier:");

        jLabel5.setText("Quantity:");

        jLabel6.setText("Total Cost:");

        jLabel7.setText("Date Received:");

        prodID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodIDActionPerformed(evt);
            }
        });

        prodQUANT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodQUANTActionPerformed(evt);
            }
        });
        prodQUANT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prodQUANTKeyReleased(evt);
            }
        });

        prodTC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prodTCKeyReleased(evt);
            }
        });

        prodDATE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prodDATEKeyReleased(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        qLabel.setText("( Enter a number )");

        tcLabel.setText("( Enter a number )");

        dLabel.setText("( mm/dd/yyyy )");
        dLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dLabelKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel8.setText("Product Information");
        jLabel8.setMaximumSize(new java.awt.Dimension(42, 15));
        jLabel8.setOpaque(true);
        jLabel8.setPreferredSize(new java.awt.Dimension(42, 15));
        jLabel8.setRequestFocusEnabled(false);

        jMenu1.setText("File");

        jMenuItem1.setText("Customers");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(prodTC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(prodQUANT, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prodSUP, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prodDESC, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prodType, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prodID, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prodDATE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qLabel)
                    .addComponent(tcLabel)
                    .addComponent(dLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(save)
                        .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(prodID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(prodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(prodDESC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(prodSUP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tcLabel)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(prodQUANT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(prodTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(prodDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(save)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
    if (prodID.getText().isEmpty() || 
        prodType.getText().isEmpty() || 
        prodDESC.getText().isEmpty() || 
        prodSUP.getText().isEmpty() || 
        prodQUANT.getText().isEmpty() || 
        prodTC.getText().isEmpty() || 
        prodDATE.getText().isEmpty()) {

      
        JOptionPane.showMessageDialog(this, "Fill all the empty boxes", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
        
        if (qLabel.getForeground().equals(Color.RED) || 
            tcLabel.getForeground().equals(Color.RED) ||  
            dLabel.getForeground().equals(Color.RED)) {

           
            JOptionPane.showMessageDialog(this, "Cannot save. Data is invalid.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
           
            JOptionPane.showMessageDialog(this, "File saved successfully!", "Save", JOptionPane.INFORMATION_MESSAGE);
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void prodIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodIDActionPerformed

    private void prodQUANTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodQUANTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodQUANTActionPerformed

    private void prodQUANTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodQUANTKeyReleased
        String quant = prodQUANT.getText().trim();
        boolean isValid = false;

    if (quant.isEmpty()) {
    
        qLabel.setForeground(Color.black);
        qLabel.setText("( Enter a number )");
        
    }
    else {  if (quant.matches("\\d+"))  {
           
            isValid = true;
            qLabel.setForeground(Color.green);
            qLabel.setText("Valid Quantity");
        }
    else {
        qLabel.setForeground(Color.red);
        qLabel.setText("Invalid Quantity");
            }   
        }
    }//GEN-LAST:event_prodQUANTKeyReleased

    private void prodTCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodTCKeyReleased
        String tc = prodTC.getText().trim();
        boolean isValid = false;
        
        if (tc.isEmpty()) {
            tcLabel.setForeground(Color.black);
            tcLabel.setText("( Enter a number )");
        }
        
        else {
            if (tc.matches("\\d+")) {
                
                isValid = true;
                tcLabel.setForeground(Color.green);
                tcLabel.setText("Valid Total Cost");
                
            }
            
            else {
                
                isValid = false;
                tcLabel.setForeground(Color.red);
                tcLabel.setText("Invalid Total Cost");
                
            }
        }
    }//GEN-LAST:event_prodTCKeyReleased

    private void prodDATEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodDATEKeyReleased
     String pDate = prodDATE.getText().trim();
     boolean isValid = false;
     
     if (pDate.isEmpty()) {
    dLabel.setText("( mm/dd/yyyy )");
    dLabel.setForeground(Color.black);  
} else {

    String dateFormatRegex = "^\\d{2}/\\d{2}/\\d{4}$";
    isValid = pDate.matches(dateFormatRegex);

    if (isValid) {
        dLabel.setForeground(Color.green);
        dLabel.setText("Valid Date");
    } else {
        dLabel.setForeground(Color.red);
        dLabel.setText("Invalid Date");
    }
}
    }//GEN-LAST:event_prodDATEKeyReleased

    private void dLabelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dLabelKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_dLabelKeyReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    Customers abc = new Customers();
    abc.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Products().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField prodDATE;
    private javax.swing.JTextField prodDESC;
    private javax.swing.JTextField prodID;
    private javax.swing.JTextField prodQUANT;
    private javax.swing.JTextField prodSUP;
    private javax.swing.JTextField prodTC;
    private javax.swing.JTextField prodType;
    private javax.swing.JLabel qLabel;
    private javax.swing.JToggleButton save;
    private javax.swing.JLabel tcLabel;
    // End of variables declaration//GEN-END:variables
}
